// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: agent/modules/process/pb/process.proto

package processpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectorSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Interval string `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *CollectorSpec) Reset() {
	*x = CollectorSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_modules_process_pb_process_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectorSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorSpec) ProtoMessage() {}

func (x *CollectorSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_modules_process_pb_process_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorSpec.ProtoReflect.Descriptor instead.
func (*CollectorSpec) Descriptor() ([]byte, []int) {
	return file_agent_modules_process_pb_process_proto_rawDescGZIP(), []int{0}
}

func (x *CollectorSpec) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CollectorSpec) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type ControllerSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ControllerSpec) Reset() {
	*x = ControllerSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_modules_process_pb_process_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControllerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerSpec) ProtoMessage() {}

func (x *ControllerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_modules_process_pb_process_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerSpec.ProtoReflect.Descriptor instead.
func (*ControllerSpec) Descriptor() ([]byte, []int) {
	return file_agent_modules_process_pb_process_proto_rawDescGZIP(), []int{1}
}

func (x *ControllerSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ModuleRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collectors  []*CollectorSpec  `protobuf:"bytes,1,rep,name=collectors,proto3" json:"collectors,omitempty"`
	Controllers []*ControllerSpec `protobuf:"bytes,2,rep,name=controllers,proto3" json:"controllers,omitempty"`
}

func (x *ModuleRegistration) Reset() {
	*x = ModuleRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_modules_process_pb_process_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRegistration) ProtoMessage() {}

func (x *ModuleRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_agent_modules_process_pb_process_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRegistration.ProtoReflect.Descriptor instead.
func (*ModuleRegistration) Descriptor() ([]byte, []int) {
	return file_agent_modules_process_pb_process_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleRegistration) GetCollectors() []*CollectorSpec {
	if x != nil {
		return x.Collectors
	}
	return nil
}

func (x *ModuleRegistration) GetControllers() []*ControllerSpec {
	if x != nil {
		return x.Controllers
	}
	return nil
}

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid               int32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid              int32   `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	User              string  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	State             string  `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CpuPercent        float64 `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes       uint64  `protobuf:"varint,6,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Command           string  `protobuf:"bytes,7,opt,name=command,proto3" json:"command,omitempty"`
	SampledAtUnixNano int64   `protobuf:"varint,8,opt,name=sampled_at_unix_nano,json=sampledAtUnixNano,proto3" json:"sampled_at_unix_nano,omitempty"`
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_modules_process_pb_process_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_agent_modules_process_pb_process_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_agent_modules_process_pb_process_proto_rawDescGZIP(), []int{3}
}

func (x *Info) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Info) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *Info) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Info) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Info) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Info) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *Info) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Info) GetSampledAtUnixNano() int64 {
	if x != nil {
		return x.SampledAtUnixNano
	}
	return 0
}

type Metrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processes []*Info `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_modules_process_pb_process_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_modules_process_pb_process_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_agent_modules_process_pb_process_proto_rawDescGZIP(), []int{4}
}

func (x *Metrics) GetProcesses() []*Info {
	if x != nil {
		return x.Processes
	}
	return nil
}

type SignalCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid    int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Signal int32 `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
}

func (x *SignalCommand) Reset() {
	*x = SignalCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agent_modules_process_pb_process_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalCommand) ProtoMessage() {}

func (x *SignalCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_modules_process_pb_process_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalCommand.ProtoReflect.Descriptor instead.
func (*SignalCommand) Descriptor() ([]byte, []int) {
	return file_agent_modules_process_pb_process_proto_rawDescGZIP(), []int{5}
}

func (x *SignalCommand) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SignalCommand) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

var File_agent_modules_process_pb_process_proto protoreflect.FileDescriptor

var file_agent_modules_process_pb_process_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x47, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x24,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x0a, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x70, 0x65, 0x63, 0x52, 0x0a, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x4d, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x74,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x22, 0xe5, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x70, 0x75, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2f, 0x0a,
	0x14, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78,
	0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x22, 0x4a,
	0x0a, 0x07, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x3f, 0x0a, 0x09, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x0d, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x42, 0x2e, 0x5a, 0x2c, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agent_modules_process_pb_process_proto_rawDescOnce sync.Once
	file_agent_modules_process_pb_process_proto_rawDescData = file_agent_modules_process_pb_process_proto_rawDesc
)

func file_agent_modules_process_pb_process_proto_rawDescGZIP() []byte {
	file_agent_modules_process_pb_process_proto_rawDescOnce.Do(func() {
		file_agent_modules_process_pb_process_proto_rawDescData = protoimpl.X.CompressGZIP(file_agent_modules_process_pb_process_proto_rawDescData)
	})
	return file_agent_modules_process_pb_process_proto_rawDescData
}

var file_agent_modules_process_pb_process_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_modules_process_pb_process_proto_goTypes = []interface{}{
	(*CollectorSpec)(nil),      // 0: telemetry.module.process.v1.CollectorSpec
	(*ControllerSpec)(nil),     // 1: telemetry.module.process.v1.ControllerSpec
	(*ModuleRegistration)(nil), // 2: telemetry.module.process.v1.ModuleRegistration
	(*Info)(nil),               // 3: telemetry.module.process.v1.Info
	(*Metrics)(nil),            // 4: telemetry.module.process.v1.Metrics
	(*SignalCommand)(nil),      // 5: telemetry.module.process.v1.SignalCommand
}
var file_agent_modules_process_pb_process_proto_depIdxs = []int32{
	0, // 0: telemetry.module.process.v1.ModuleRegistration.collectors:type_name -> telemetry.module.process.v1.CollectorSpec
	1, // 1: telemetry.module.process.v1.ModuleRegistration.controllers:type_name -> telemetry.module.process.v1.ControllerSpec
	3, // 2: telemetry.module.process.v1.Metrics.processes:type_name -> telemetry.module.process.v1.Info
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agent_modules_process_pb_process_proto_init() }
func file_agent_modules_process_pb_process_proto_init() {
	if File_agent_modules_process_pb_process_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agent_modules_process_pb_process_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectorSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_modules_process_pb_process_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControllerSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_modules_process_pb_process_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_modules_process_pb_process_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_modules_process_pb_process_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agent_modules_process_pb_process_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agent_modules_process_pb_process_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_modules_process_pb_process_proto_goTypes,
		DependencyIndexes: file_agent_modules_process_pb_process_proto_depIdxs,
		MessageInfos:      file_agent_modules_process_pb_process_proto_msgTypes,
	}.Build()
	File_agent_modules_process_pb_process_proto = out.File
	file_agent_modules_process_pb_process_proto_rawDesc = nil
	file_agent_modules_process_pb_process_proto_goTypes = nil
	file_agent_modules_process_pb_process_proto_depIdxs = nil
}
